networks:
  inspire-open-webui:
    external: true
  tunnel:
    external: true

volumes:
  qdrant:
  open-webui:
  postgres:
  redis:
  redis-insight:

services:
  postgres:
    image: postgres
    # container_name: db
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=openwebui
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=openwebui
    # ports:
    #   - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', -U, openwebui]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inspire-open-webui
  redis:
    image: redis:8-alpine
    # container_name: redis
    restart: unless-stopped
    command: ['redis-server', '--requirepass', myredispassword]
    volumes:
      - redis:/data
    # ports:
    #   - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, --raw, incr, ping]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inspire-open-webui

  qdrant:
    image: qdrant/qdrant:latest
    # container_name: qdrant
    # ports:
    #   - '6333:6333' # HTTP API
    #   - '6334:6334' # gRPC API
    volumes:
      - qdrant:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=*
    networks:
      - inspire-open-webui

  tika:
    image: apache/tika:latest-full
    # ports:
    #   - '9998:9998'
    restart: unless-stopped
    networks:
      - inspire-open-webui

  open-webui:
    # image: ghcr.io/open-webui/open-webui:main
    image: hadesgod/inspireivf-open-webui:latest
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    container_name: inspire-ivf-open-webui
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # ports:
    #   - '3000:8080'
    environment:
      WEBUI_NAME: 'InspireIVF'
      # ** OLLAMA **
      ENABLE_OLLAMA_API: True
      OLLAMA_BASE_URL: http://localhost:11434
      # OLLAMA_BASE_URLS: http://host-one:11434;http://host-two:11434

      # ** OpenAI **
      # ENABLE_OPENAI_API: True
      # OPENAI_API_BASE_URL: https://api.openai.com/v1
      # OPENAI_API_BASE_URLS: https://api.openai.com/v1,http://host-one:11434;http://host-two:11434
      # OPENAI_API_KEY: sk-124781258123
      # OPENAI_API_KEYS: sk-124781258123;sk-4389759834759834

      # ** Vector DB **
      VECTOR_DB: qdrant # chroma, elasticsearch, milvus, opensearch, pgvector, qdrant, pinecone, s3vector, oracle23ai
      # QDRANT_API_KEY: abc
      QDRANT_URI: http://qdrant:6333
      # QDRANT_PREFER_GRPC: False

      # ** Content Extraction Engine **
      # ## if use docling ##
      # CONTENT_EXTRACTION_ENGINE: docling
      # DOCLING_SERVER_URL: http://docling:5001
      # ## if use tika ##
      CONTENT_EXTRACTION_ENGINE: tika
      DOCLING_SERVER_URL: http://tika:9998

      # ** RAG Embedding Engine **
      # RAG_EMBEDDING_ENGINE: openai | ollama
      # RAG_EMBEDDING_MODEL:

      # ** Database **
      DATABASE_URL: postgresql://openwebui:mysecretpassword@postgres:5432/openwebui
      DATABASE_TYPE: postgresql

      # ** Redis **
      REDIS_URL: redis://default:myredispassword@redis:6379

    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - inspire-open-webui
      - tunnel
